### ISSUE TITLE
[epic] Obsidian Flowershow Plugin v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/obsidian-flowershow#1]
When I have my obsidian vault i can install the flowershow plugin and publish directly from obsidian with flowershow with ease

- Install flowershow plugin
- Setup github repo (copy the template)
- Setup deploy
- Start publishing
- Profit 🚀

We can reuse and taking inspiration from https://github.com/oleeskild/obsidian-digital-garden

## Estimate

- [x] How long would it take to get an alpha? a beta? **✅2023-04-28 1-2 days for MVP/POC, 2 days for implementing all the features we need and polishing = 3-4 days, but rather 4-5 cuz I always underestimate 😅**

## Acceptance

- [x] #2 
	- [x] We have a repo for the project at `obsidian-flowershow`
	- [x] We have an obsidian plugin
- [x] #3 **PR: #4**
- [x] Basic instructions for use (e.g. clone flowershow template, get github access token) in README or similar **PR: #4**
  - [ ] #7
- [x] Obsidian plugin is published in obsidian community plugin list and installable by users

## Tasks
- [x] create a separate repo for Flowershow template (users need to clone it to their own GH, so we don't want them copy the whole monorepo) https://github.com/datopian/flowershow-template

**Comment by mranh2na** [comment]
I do wait for this feature. Really need it.

**Comment by rufuspollock** [comment]
FIXED. All done as of early August.
