### ISSUE TITLE
Publish to Obsidian's community plugins

### ISSUE THREAD

**Issue by olayway** [datopian/obsidian-flowershow#8]
Our plugin is still pending review - see https://github.com/obsidianmd/obsidian-releases/pulls
and https://github.com/obsidianmd/obsidian-releases/pull/1967 **💬 based on a review they are only merging a couple of a plugins a week at best and most recent ones were submitted at start of May. So guess that we just wait a bit more.**

## Acceptance
- [x] our plugin has been published and can be found under community plugins in Obsidian and installed

## Tasks
- [x] tests **tested and applied fixes**
  - [x] test on MacOS
  - [x] test on Windows
  - [x] test on Linux
- [x] create a fork and PR against obsidianmd/obsidian-releases with our plugin added

**Comment by louis030195** [comment]
I would be happy to pay for flowershow (between $5 to $20 monthly) if it can replace publish and does not require a lot of effort to migrate from my side. Awaiting for the plugin to be available in the community list :)

**Comment by rufuspollock** [comment]
FIXED. This was published back in July 🎉
